version: '3.8'

services:
  database:
    image: postgres:14.4-alpine3.16
    restart: 'no'
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "admin", "-d", "obodeflix" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    environment:
      - POSTGRES_DB=obodeflix
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
